/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuildingRouteImport } from './routes/building'
import { Route as FilmRouteImport } from './routes/film'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as NeighborhoodRouteImport } from './routes/neighborhood'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as LgcManage8673cd970652f87aIndexRouteImport } from './routes/lgc-manage-8673cd970652f87a/index'
import { Route as LgcManage8673cd970652f87aSlugRouteImport } from './routes/lgc-manage-8673cd970652f87a/$slug'
import { Route as ResidencesSlugRouteImport } from './routes/residences.$slug'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as LgcManage8673cd970652f87aSlugPhotosRouteImport } from './routes/lgc-manage-8673cd970652f87a/$slug.photos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingRoute = BuildingRouteImport.update({
  id: '/building',
  path: '/building',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmRoute = FilmRouteImport.update({
  id: '/film',
  path: '/film',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const NeighborhoodRoute = NeighborhoodRouteImport.update({
  id: '/neighborhood',
  path: '/neighborhood',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const LgcManage8673cd970652f87aIndexRoute =
  LgcManage8673cd970652f87aIndexRouteImport.update({
    id: '/lgc-manage-8673cd970652f87a/',
    path: '/lgc-manage-8673cd970652f87a/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LgcManage8673cd970652f87aSlugRoute =
  LgcManage8673cd970652f87aSlugRouteImport.update({
    id: '/lgc-manage-8673cd970652f87a/$slug',
    path: '/lgc-manage-8673cd970652f87a/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResidencesSlugRoute = ResidencesSlugRouteImport.update({
  id: '/residences/$slug',
  path: '/residences/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const LgcManage8673cd970652f87aSlugPhotosRoute =
  LgcManage8673cd970652f87aSlugPhotosRouteImport.update({
    id: '/photos',
    path: '/photos',
    getParentRoute: () => LgcManage8673cd970652f87aSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/building': typeof BuildingRoute
  '/film': typeof FilmRoute
  '/imprint': typeof ImprintRoute
  '/mcp': typeof McpRoute
  '/neighborhood': typeof NeighborhoodRoute
  '/privacy': typeof PrivacyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/lgc-manage-8673cd970652f87a/$slug': typeof LgcManage8673cd970652f87aSlugRouteWithChildren
  '/residences/$slug': typeof ResidencesSlugRoute
  '/lgc-manage-8673cd970652f87a/': typeof LgcManage8673cd970652f87aIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/lgc-manage-8673cd970652f87a/$slug/photos': typeof LgcManage8673cd970652f87aSlugPhotosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/building': typeof BuildingRoute
  '/film': typeof FilmRoute
  '/imprint': typeof ImprintRoute
  '/mcp': typeof McpRoute
  '/neighborhood': typeof NeighborhoodRoute
  '/privacy': typeof PrivacyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/lgc-manage-8673cd970652f87a/$slug': typeof LgcManage8673cd970652f87aSlugRouteWithChildren
  '/residences/$slug': typeof ResidencesSlugRoute
  '/lgc-manage-8673cd970652f87a': typeof LgcManage8673cd970652f87aIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/lgc-manage-8673cd970652f87a/$slug/photos': typeof LgcManage8673cd970652f87aSlugPhotosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/building': typeof BuildingRoute
  '/film': typeof FilmRoute
  '/imprint': typeof ImprintRoute
  '/mcp': typeof McpRoute
  '/neighborhood': typeof NeighborhoodRoute
  '/privacy': typeof PrivacyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/lgc-manage-8673cd970652f87a/$slug': typeof LgcManage8673cd970652f87aSlugRouteWithChildren
  '/residences/$slug': typeof ResidencesSlugRoute
  '/lgc-manage-8673cd970652f87a/': typeof LgcManage8673cd970652f87aIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/lgc-manage-8673cd970652f87a/$slug/photos': typeof LgcManage8673cd970652f87aSlugPhotosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/building'
    | '/film'
    | '/imprint'
    | '/mcp'
    | '/neighborhood'
    | '/privacy'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/lgc-manage-8673cd970652f87a/$slug'
    | '/residences/$slug'
    | '/lgc-manage-8673cd970652f87a/'
    | '/.mcp/invoke-tool/$tool'
    | '/lgc-manage-8673cd970652f87a/$slug/photos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/building'
    | '/film'
    | '/imprint'
    | '/mcp'
    | '/neighborhood'
    | '/privacy'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/lgc-manage-8673cd970652f87a/$slug'
    | '/residences/$slug'
    | '/lgc-manage-8673cd970652f87a'
    | '/.mcp/invoke-tool/$tool'
    | '/lgc-manage-8673cd970652f87a/$slug/photos'
  id:
    | '__root__'
    | '/'
    | '/building'
    | '/film'
    | '/imprint'
    | '/mcp'
    | '/neighborhood'
    | '/privacy'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/lgc-manage-8673cd970652f87a/$slug'
    | '/residences/$slug'
    | '/lgc-manage-8673cd970652f87a/'
    | '/.mcp/invoke-tool/$tool'
    | '/lgc-manage-8673cd970652f87a/$slug/photos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildingRoute: typeof BuildingRoute
  FilmRoute: typeof FilmRoute
  ImprintRoute: typeof ImprintRoute
  McpRoute: typeof McpRoute
  NeighborhoodRoute: typeof NeighborhoodRoute
  PrivacyRoute: typeof PrivacyRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  LgcManage8673cd970652f87aSlugRoute: typeof LgcManage8673cd970652f87aSlugRouteWithChildren
  ResidencesSlugRoute: typeof ResidencesSlugRoute
  LgcManage8673cd970652f87aIndexRoute: typeof LgcManage8673cd970652f87aIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/building': {
      id: '/building'
      path: '/building'
      fullPath: '/building'
      preLoaderRoute: typeof BuildingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/film': {
      id: '/film'
      path: '/film'
      fullPath: '/film'
      preLoaderRoute: typeof FilmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neighborhood': {
      id: '/neighborhood'
      path: '/neighborhood'
      fullPath: '/neighborhood'
      preLoaderRoute: typeof NeighborhoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lgc-manage-8673cd970652f87a/': {
      id: '/lgc-manage-8673cd970652f87a/'
      path: '/lgc-manage-8673cd970652f87a'
      fullPath: '/lgc-manage-8673cd970652f87a/'
      preLoaderRoute: typeof LgcManage8673cd970652f87aIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lgc-manage-8673cd970652f87a/$slug': {
      id: '/lgc-manage-8673cd970652f87a/$slug'
      path: '/lgc-manage-8673cd970652f87a/$slug'
      fullPath: '/lgc-manage-8673cd970652f87a/$slug'
      preLoaderRoute: typeof LgcManage8673cd970652f87aSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residences/$slug': {
      id: '/residences/$slug'
      path: '/residences/$slug'
      fullPath: '/residences/$slug'
      preLoaderRoute: typeof ResidencesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lgc-manage-8673cd970652f87a/$slug/photos': {
      id: '/lgc-manage-8673cd970652f87a/$slug/photos'
      path: '/photos'
      fullPath: '/lgc-manage-8673cd970652f87a/$slug/photos'
      preLoaderRoute: typeof LgcManage8673cd970652f87aSlugPhotosRouteImport
      parentRoute: typeof LgcManage8673cd970652f87aSlugRoute
    }
  }
}

interface LgcManage8673cd970652f87aSlugRouteChildren {
  LgcManage8673cd970652f87aSlugPhotosRoute: typeof LgcManage8673cd970652f87aSlugPhotosRoute
}

const LgcManage8673cd970652f87aSlugRouteChildren: LgcManage8673cd970652f87aSlugRouteChildren =
  {
    LgcManage8673cd970652f87aSlugPhotosRoute:
      LgcManage8673cd970652f87aSlugPhotosRoute,
  }

const LgcManage8673cd970652f87aSlugRouteWithChildren =
  LgcManage8673cd970652f87aSlugRoute._addFileChildren(
    LgcManage8673cd970652f87aSlugRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildingRoute: BuildingRoute,
  FilmRoute: FilmRoute,
  ImprintRoute: ImprintRoute,
  McpRoute: McpRoute,
  NeighborhoodRoute: NeighborhoodRoute,
  PrivacyRoute: PrivacyRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  LgcManage8673cd970652f87aSlugRoute:
    LgcManage8673cd970652f87aSlugRouteWithChildren,
  ResidencesSlugRoute: ResidencesSlugRoute,
  LgcManage8673cd970652f87aIndexRoute: LgcManage8673cd970652f87aIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
