/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResidencesIndexRouteImport } from './routes/residences.index'
import { Route as ResidencesSlugRouteImport } from './routes/residences.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidencesIndexRoute = ResidencesIndexRouteImport.update({
  id: '/residences/',
  path: '/residences/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidencesSlugRoute = ResidencesSlugRouteImport.update({
  id: '/residences/$slug',
  path: '/residences/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/residences/$slug': typeof ResidencesSlugRoute
  '/residences/': typeof ResidencesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/residences/$slug': typeof ResidencesSlugRoute
  '/residences': typeof ResidencesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/residences/$slug': typeof ResidencesSlugRoute
  '/residences/': typeof ResidencesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/residences/$slug' | '/residences/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/residences/$slug' | '/residences'
  id: '__root__' | '/' | '/residences/$slug' | '/residences/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResidencesSlugRoute: typeof ResidencesSlugRoute
  ResidencesIndexRoute: typeof ResidencesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residences/': {
      id: '/residences/'
      path: '/residences'
      fullPath: '/residences/'
      preLoaderRoute: typeof ResidencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residences/$slug': {
      id: '/residences/$slug'
      path: '/residences/$slug'
      fullPath: '/residences/$slug'
      preLoaderRoute: typeof ResidencesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResidencesSlugRoute: ResidencesSlugRoute,
  ResidencesIndexRoute: ResidencesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
