/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuildingRouteImport } from './routes/building'
import { Route as FilmRouteImport } from './routes/film'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as NeighborhoodRouteImport } from './routes/neighborhood'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResidencesSlugRouteImport } from './routes/residences.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingRoute = BuildingRouteImport.update({
  id: '/building',
  path: '/building',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmRoute = FilmRouteImport.update({
  id: '/film',
  path: '/film',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const NeighborhoodRoute = NeighborhoodRouteImport.update({
  id: '/neighborhood',
  path: '/neighborhood',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidencesSlugRoute = ResidencesSlugRouteImport.update({
  id: '/residences/$slug',
  path: '/residences/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/building': typeof BuildingRoute
  '/film': typeof FilmRoute
  '/imprint': typeof ImprintRoute
  '/neighborhood': typeof NeighborhoodRoute
  '/privacy': typeof PrivacyRoute
  '/residences/$slug': typeof ResidencesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/building': typeof BuildingRoute
  '/film': typeof FilmRoute
  '/imprint': typeof ImprintRoute
  '/neighborhood': typeof NeighborhoodRoute
  '/privacy': typeof PrivacyRoute
  '/residences/$slug': typeof ResidencesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/building': typeof BuildingRoute
  '/film': typeof FilmRoute
  '/imprint': typeof ImprintRoute
  '/neighborhood': typeof NeighborhoodRoute
  '/privacy': typeof PrivacyRoute
  '/residences/$slug': typeof ResidencesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/building'
    | '/film'
    | '/imprint'
    | '/neighborhood'
    | '/privacy'
    | '/residences/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/building'
    | '/film'
    | '/imprint'
    | '/neighborhood'
    | '/privacy'
    | '/residences/$slug'
  id:
    | '__root__'
    | '/'
    | '/building'
    | '/film'
    | '/imprint'
    | '/neighborhood'
    | '/privacy'
    | '/residences/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildingRoute: typeof BuildingRoute
  FilmRoute: typeof FilmRoute
  ImprintRoute: typeof ImprintRoute
  NeighborhoodRoute: typeof NeighborhoodRoute
  PrivacyRoute: typeof PrivacyRoute
  ResidencesSlugRoute: typeof ResidencesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/building': {
      id: '/building'
      path: '/building'
      fullPath: '/building'
      preLoaderRoute: typeof BuildingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/film': {
      id: '/film'
      path: '/film'
      fullPath: '/film'
      preLoaderRoute: typeof FilmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neighborhood': {
      id: '/neighborhood'
      path: '/neighborhood'
      fullPath: '/neighborhood'
      preLoaderRoute: typeof NeighborhoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residences/$slug': {
      id: '/residences/$slug'
      path: '/residences/$slug'
      fullPath: '/residences/$slug'
      preLoaderRoute: typeof ResidencesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildingRoute: BuildingRoute,
  FilmRoute: FilmRoute,
  ImprintRoute: ImprintRoute,
  NeighborhoodRoute: NeighborhoodRoute,
  PrivacyRoute: PrivacyRoute,
  ResidencesSlugRoute: ResidencesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
